name: Production Build

on:
  push:
    branches:
      - master

jobs:
  build:
    # 使用最新版ubantu虚拟机运行
    runs-on: ubuntu-latest

    steps:
      # from: https://github.com/actions/checkout
      - name: 本工作流
        uses: actions/checkout@master

      # 安装最新版 Node.js
      # from: https://github.com/actions/setup-node
      - name: 安装 Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: 安装 yarn
        run: |
          npm install yarn -g

      - name: 安装项目依赖
        run: |
          yarn install

      - name: 测试项目
        run: |
          yarn test

      - name: 构建项目并打包发布
        run: |
          npm run publish:stable
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: 刷新 jsDelivr 缓存
        run: |
          curl -v -m 60 "https://purge.jsdelivr.net/npm/mediawiki-inpageedit@latest/"
          curl -v -m 60 "https://purge.jsdelivr.net/npm/mediawiki-inpageedit@latest/dist/"
          curl -v -m 30 "https://purge.jsdelivr.net/npm/mediawiki-inpageedit@latest/src/skin/"
          curl -v -m 30 "https://purge.jsdelivr.net/npm/mediawiki-inpageedit@latest/i18n/languages.json"
